import logging
from datetime import datetime, timedelta, timezone
from typing import List, Optional
from strands import tool
from src.models.core import Inventory, DemandForecast, Transaction

logger = logging.getLogger(__name__)

# Mock Inventory Data
MOCK_INVENTORY = [
    Inventory(product_id="p1", stock_level=50, reorder_point=20, last_restock_at=datetime.now(timezone.utc) - timedelta(days=5)),
    Inventory(product_id="p2", stock_level=12, reorder_point=15, last_restock_at=datetime.now(timezone.utc) - timedelta(days=10)),
]

# Mock Sales Data (Reuse Transaction)
MOCK_SALES = [
    Transaction(transaction_id="s1", customer_id="c1", product_id="p1", amount=50.0, quantity=1, timestamp=datetime.now(timezone.utc) - timedelta(days=2)),
    Transaction(transaction_id="s2", customer_id="c2", product_id="p1", amount=50.0, quantity=1, timestamp=datetime.now(timezone.utc) - timedelta(days=1)),
    Transaction(transaction_id="s3", customer_id="c3", product_id="p2", amount=20.0, quantity=2, timestamp=datetime.now(timezone.utc) - timedelta(days=3)),
]

@tool
def get_inventory_status(product_id: str) -> Optional[Inventory]:
    """
    Retrieves the current inventory status for a specific product ID.
    """
    logger.info(f"Checking inventory for product: {product_id}")
    for item in MOCK_INVENTORY:
        if item.product_id == product_id:
            return item
    return None

@tool
def get_historical_demand(product_id: str, days: int = 30) -> List[Transaction]:
    """
    Fetches historical sales transactions for a product within a specified number of days.
    """
    logger.info(f"Fetching historical demand for product: {product_id} over {days} days")
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    return [t for t in MOCK_SALES if t.product_id == product_id and t.timestamp >= cutoff]

@tool
def save_demand_forecast(forecast: DemandForecast) -> bool:
    """
    Saves a demand forecast generated by the agent to the system.
    """
    logger.info(f"Saving demand forecast for product {forecast.product_id}: {forecast.predicted_quantity}")
    # In a real system, this would write to a DB or LanceDB
    return True
